apiVersion: "v1"
kind: "Pod"
metadata:
  name: "jenkins-slave"
  labels:
    name: "jenkins-slave"
spec:
    containers:
      - name: "jenkins-slave"
        image: "tjkemper/jnlp-slave:0.4"
        env:
          - name: "JENKINS_URL"
            value: "http://100.68.13.101:80"
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
